FROM node:20-alpine

WORKDIR /app

COPY . .

WORKDIR /app/.artifacts/jira-work-report
RUN npm install

EXPOSE 5173

CMD sh -c 'export VITE_BASE_PATH=$PREVIEW_BASE_PATH && npm run build && npx vite preview --host 0.0.0.0 --port 5173'
